import React from "react";
import { cn } from "../../lib/utils";
import { AlertTriangle, Sparkles, ShieldAlert } from "lucide-react";

export function ScoreCard({ score = 0, label = "Specification Readiness", size = "md", className }) {
  const numScore = Number(score) || 0;
  
  let color = "text-emerald-600 border-emerald-500 bg-emerald-50/50";
  let tierLabel = "High Readiness";
  let tierDesc = "Specifications align closely with standard parameters.";

  if (numScore < 60) {
    color = "text-rose-600 border-rose-500 bg-rose-50/50";
    tierLabel = "Critical Gaps";
    tierDesc = "Multiple mandatory standards and testing criteria are missing.";
  } else if (numScore < 80) {
    color = "text-amber-600 border-amber-500 bg-amber-50/50";
    tierLabel = "Moderate Readiness";
    tierDesc = "Requires attention on highlighted technical parameters.";
  }

  return (
    <div className={cn("flex items-center gap-4 p-4 rounded-xl border bg-white shadow-sm", className)}>
      <div className={cn("w-16 h-16 rounded-full flex flex-col items-center justify-center border-4 font-display font-bold shrink-0", color)}>
        <span className="text-xl leading-none">{numScore}</span>
        <span className="text-[9px] uppercase font-semibold text-slate-500">/ 100</span>
      </div>
      <div>
        <div className="text-xs font-semibold uppercase tracking-wider text-slate-500">{label}</div>
        <div className="text-sm font-bold text-slate-900 mt-0.5">{tierLabel}</div>
        <div className="text-xs text-slate-500 mt-0.5">{tierDesc}</div>
      </div>
    </div>
  );
}

export function MetricCard({ title, value, subtitle, icon: Icon, color = "blue", className }) {
  const colors = {
    blue: "bg-blue-50 text-blue-700 border-blue-100",
    amber: "bg-amber-50 text-amber-700 border-amber-100",
    emerald: "bg-emerald-50 text-emerald-700 border-emerald-100",
    purple: "bg-purple-50 text-purple-700 border-purple-100",
  };

  return (
    <div className={cn("p-5 rounded-lg bg-white border border-slate-200/90 shadow-sm flex items-start justify-between", className)}>
      <div>
        <p className="text-xs font-semibold uppercase tracking-wider text-slate-500">{title}</p>
        <h3 className="text-2xl font-bold text-slate-900 mt-1 font-display tracking-tight">{value}</h3>
        {subtitle && <p className="text-xs text-slate-500 mt-1">{subtitle}</p>}
      </div>
      {Icon && (
        <div className={cn("p-2.5 rounded-lg border", colors[color] || colors.blue)}>
          <Icon className="w-5 h-5" />
        </div>
      )}
    </div>
  );
}

export function PrototypeBanner({ className, message }) {
  return (
    <div className={cn("p-3.5 rounded-lg bg-amber-50/90 border border-amber-200 text-amber-900 flex items-start gap-3 text-xs", className)}>
      <AlertTriangle className="w-4 h-4 text-amber-700 shrink-0 mt-0.5" />
      <div className="flex-1">
        <span className="font-semibold text-amber-950">PROTOTYPE ANALYSIS (PHASE 1): </span>
        {message || "Findings and standards recommendations are generated by the Phase 1 prototype evaluation engine. All references must be verified against official BIS publications before inclusion in legal tender documents."}
      </div>
    </div>
  );
}
