import React, { useState, useEffect } from "react";
import { Link, useParams } from "react-router-dom";
import { FileText, Eye, Download, Printer, ShieldCheck, CheckCircle2, ChevronRight } from "lucide-react";
import { reportService } from "../services/reportService";
import { Breadcrumb, Table, LoadingState, ErrorState } from "../components/common/FeedbackAndNavigation";
import { Modal } from "../components/common/Modal";
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "../components/common/Card";
import { StatusBadge, Badge } from "../components/common/Badge";
import { PrototypeBanner } from "../components/common/Indicators";
import { Button } from "../components/common/Button";
import { formatDate, formatDateTime } from "../lib/utils";

export function Reports() {
  const { id } = useParams();
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [selectedReport, setSelectedReport] = useState(null);

  const loadReports = async () => {
    setLoading(true);
    setError("");
    try {
      const data = await reportService.listReports();
      setReports(data);
      if (id) {
        const single = await reportService.getReportById(id);
        setSelectedReport(single);
      }
    } catch (err) {
      setError("Failed to load reports archive.");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadReports();
  }, [id]);

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="space-y-6 max-w-7xl mx-auto">
      <div>
        <Breadcrumb
          items={[
            { label: "Dashboard", href: "/" },
            { label: "Procurement Advisory Reports" },
          ]}
        />
        <div className="flex items-center justify-between mt-2">
          <div>
            <h2 className="text-xl sm:text-2xl font-bold text-slate-900 font-display tracking-tight">
              Procurement Advisory Reports
            </h2>
            <p className="text-xs text-slate-500 mt-0.5">
              Compiled technical intelligence reports, compliance checklists, and standard verification summaries.
            </p>
          </div>
        </div>
      </div>

      <PrototypeBanner message="Advisory reports are compiled for procurement review. Legal tenders require verification against official BIS gazette notices." />

      {loading ? (
        <LoadingState message="Loading generated reports archive..." />
      ) : error ? (
        <ErrorState title="Error Loading Reports" message={error} onRetry={loadReports} />
      ) : (
        <Card>
          <Table className="gov-table">
            <thead>
              <tr>
                <th>Report ID</th>
                <th>Procurement Item / Analysis</th>
                <th>Generated By</th>
                <th>Generated Date</th>
                <th>Status</th>
                <th className="text-right">Actions</th>
              </tr>
            </thead>
            <tbody>
              {reports.length === 0 ? (
                <tr>
                  <td colSpan={6} className="text-center py-8 text-slate-400 text-xs">
                    No advisory reports compiled yet.
                  </td>
                </tr>
              ) : (
                reports.map((r) => (
                  <tr key={r.id} className="hover:bg-slate-50/80 transition-colors">
                    <td className="font-mono text-xs font-bold text-navy-900">
                      #RPT-{String(r.id).padStart(4, "0")}
                    </td>
                    <td>
                      <div className="font-semibold text-slate-900 text-xs">
                        {r.report_data_json?.product_name || `Analysis #ANL-${r.analysis_id}`}
                      </div>
                      <p className="text-[11px] text-slate-500 line-clamp-1">{r.summary}</p>
                    </td>
                    <td className="text-xs text-slate-600">
                      {r.generator_user?.name || "Procurement Officer"}
                    </td>
                    <td className="text-xs text-slate-500 whitespace-nowrap">
                      {formatDateTime(r.created_at)}
                    </td>
                    <td>
                      <StatusBadge status={r.status} />
                    </td>
                    <td className="text-right whitespace-nowrap">
                      <div className="flex items-center justify-end gap-1.5">
                        <Button
                          size="sm"
                          variant="secondary"
                          icon={Eye}
                          onClick={() => setSelectedReport(r)}
                        >
                          Preview Report
                        </Button>
                      </div>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </Table>
        </Card>
      )}

      {/* Report Preview Modal */}
      <Modal
        isOpen={!!selectedReport}
        onClose={() => setSelectedReport(null)}
        title={`Procurement Advisory Brief: #RPT-${String(selectedReport?.id).padStart(4, "0")}`}
        description="Official procurement advisory compilation with Indian Standards mapping"
        maxWidth="max-w-4xl"
      >
        {selectedReport && (
          <div className="space-y-6 text-xs text-slate-700">
            {/* Header section in modal */}
            <div className="p-4 rounded-lg bg-slate-50 border border-slate-200 flex items-center justify-between">
              <div>
                <h4 className="text-sm font-bold text-slate-900">
                  {selectedReport.report_data_json?.report_title || "Procurement Advisory Report"}
                </h4>
                <p className="text-[11px] text-slate-500 mt-0.5">
                  Compiled on {formatDateTime(selectedReport.created_at)} • Generated for Analysis #ANL-{selectedReport.analysis_id}
                </p>
              </div>
              <Button size="sm" variant="outline" icon={Printer} onClick={handlePrint}>
                Print Report
              </Button>
            </div>

            {/* Score & Summary */}
            <div className="p-4 rounded-lg border bg-white flex items-center gap-4">
              <div className="w-14 h-14 rounded-full bg-emerald-50 border-4 border-emerald-500 flex flex-col items-center justify-center font-display font-bold text-emerald-800 text-lg shrink-0">
                {selectedReport.report_data_json?.readiness_score || 85}
              </div>
              <div>
                <h5 className="font-bold text-slate-900">Specification Readiness Rating: High</h5>
                <p className="text-slate-600 mt-0.5">{selectedReport.summary}</p>
              </div>
            </div>

            {/* Standards Recommendations */}
            <div>
              <h5 className="font-bold text-slate-900 text-sm mb-2">Recommended Indian Standards</h5>
              <div className="space-y-2">
                {(selectedReport.report_data_json?.standards_recommendations || []).map((s, idx) => (
                  <div key={idx} className="p-3 rounded-lg border bg-slate-50 flex items-start justify-between gap-3">
                    <div>
                      <span className="font-mono font-bold text-navy-900">{s.is_number}</span>
                      <span className="text-slate-600 ml-2">{s.title}</span>
                      <p className="text-[11px] text-slate-500 mt-1">{s.reason}</p>
                    </div>
                    <span className="px-2 py-0.5 rounded bg-emerald-100 text-emerald-800 font-bold shrink-0">
                      {s.relevance_score}
                    </span>
                  </div>
                ))}
              </div>
            </div>

            {/* Findings */}
            <div>
              <h5 className="font-bold text-slate-900 text-sm mb-2">Identified Attention & Risk Items</h5>
              <div className="space-y-2">
                {(selectedReport.report_data_json?.risk_findings || []).map((f, idx) => (
                  <div key={idx} className="p-3 rounded-lg border bg-amber-50/50 border-amber-200">
                    <span className="font-bold text-amber-950 uppercase text-[10px] px-1.5 py-0.2 rounded bg-amber-200 mr-2">
                      {f.severity}
                    </span>
                    <span className="font-semibold text-slate-900">{f.title}</span>
                    <p className="text-slate-600 mt-1">{f.description}</p>
                    {f.recommendation && (
                      <p className="text-[11px] text-slate-700 font-medium mt-1">
                        → Action: {f.recommendation}
                      </p>
                    )}
                  </div>
                ))}
              </div>
            </div>

            <div className="p-3 rounded bg-slate-100 text-[11px] text-slate-500 italic">
              Disclaimer: {selectedReport.report_data_json?.disclaimer}
            </div>

            <div className="flex justify-end gap-2 pt-3 border-t">
              <Button variant="secondary" onClick={() => setSelectedReport(null)}>
                Close Preview
              </Button>
            </div>
          </div>
        )}
      </Modal>
    </div>
  );
}
